### PR TITLE
Youtube Clone - Embedded Images and Video

### PR DESCRIPTION
**Pull request by adamclasic**
Pull request for feature-branch containing the project "Embedding Images and Video". This project is a collaborative project and is a replica of the YouTube page version so it is made up of a navigation bar, an embedded video player, a social media section. It contains as well a recommended section on the right side with video thumbnails and title descriptions of each video.

[Live Demo Link](https://rawcdn.githack.com/adamclasic/Youtube-clone/99cc02a77534c058a569f31ce57489762cc81ea8/index.html)

### CODE REVIEW

**Review by nikasulo — APPROVED** [review]
# WOW! :drooling_face: 
Your project looks so real @adamclasic and @Mupa1 :+1: I would love to approve it for you, however, there is one tiny detail you must address, please see below.

#### Descriptive PR
You need a more descriptive PR as it is a hard requirement. Consider describing the work you have completed in the branch in as much detail as you can and even include a link to the live project to speed up your review!
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# WOW! :drooling_face: 
Your project looks so real @adamclasic and @Mupa1 :+1: I would love to approve it for you, however, there is one tiny detail you must address, please see below.

#### Descriptive PR
You need a more descriptive PR as it is a hard requirement. Consider describing the work you have completed in the branch in as much detail as you can and even include a link to the live project to speed up your review!
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by nikasulo** [comment]
# Please ignore the approval above, I am requesting changes.

**Comment by Mupa1** [comment]
Thanks, updated

**Comment by rOluochKe** [comment]
@adamclasic and @Mupa1 Good job so far. However, you have a few changes you need to make.

- Make the search bar a bit smaller as in youtube
search bar
- On the right end of your navigation, add at least 3 icons
3 buttons
- Add comments section in your layout
add comment
- Add .gitignore file to your project and prevent files like .vscode not to be pushed to the remote repository

Once you make all these changes, resubmit your project for review.
If you are having problems, reach out for help in slack, team or mentor. All the best

**Comment by shshamim63** [comment]
### Status :white_check_mark: [Required Changes] :white_check_mark: 
___
Hi @adamclasic  and @Mupa1 :wave: ,
Awesome job :open_mouth:, it is almost like the original one. Project contains readme, PR does not contain a meaningful title. Maybe you can rename it something like related to this project. I can see the name of the branch is `Feature-Branch`. So definitely it contains a feature. So the  PR should contain a long title based on the task covered on this branch. But the main issue that is blocking me to approve this project is a really small issue, but approval for this project demands a tag, that is `all issues have been resolved`. Though a simple issue but constrain must be followed.
___
### :spades: [Mandatory Changes] :spades: 
___
1. Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
I can see only one issue in this line.
https://github.com/adamclasic/Youtube-clone/blob/b390fa06d58841324a5759fe5cc2d6f3eb7754fc/index.html#L26
___
#### Please fix the above mentioned issue and send a review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

**Review by imhta — APPROVED** [review]
# Project approved 🎉 

### Hello  @adamclasic @Mupa1  , 👋 You have done a great job in this project 👏 




----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Comment by Mupa1** [comment]
Nice job @adamclasic. Happy coding

**Pull request merged**
